coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

flags:
  fast-tests:
    paths:
      - src
    carryforward: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "examples"
  - "docs"
  - "**/tests/**"